name: Build and Push Docker Image

on:
  push:
    branches:
      - rocky

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
 
    - name: Free up some disk space.
      uses: jlumbroso/free-disk-space@f68fdb76e2ea636224182cfb7377ff9a1708f9b8
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker HUB
      run: echo ${{ secrets.DOCKERPASSWORD }} | docker login --username omanshkrishn --password-stdin

    - name: Build and push Docker image
      run: |
        docker buildx create --use
        docker buildx inspect --bootstrap
        docker buildx build -t omanshkrishn/materialgram:rockylatest -t omanshkrishn/materialgram:rocky$(date +%Y%m%d%H%M%S) --platform linux/amd64 . --push
