name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 */14 * *'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker HUB
      run: echo ${{ secrets.PASSWORD }} | docker login --username ghazzor --password-stdin

    - name: Build and push Docker image
      run: |
        docker buildx create --use
        docker buildx inspect --bootstrap
        docker buildx build -t ghazzor/ubuntu-tg:latest -t ghazzor/ubuntu-tg:$(date +%Y%m%d%H%M%S) --platform linux/amd64 . --push
